### ISSUE TITLE
check_that vs. assert_that

### ISSUE THREAD

**Issue by anarang** [lemoncheesecake/lemoncheesecake#10]
I understand the difference which is mentioned in the docs but I still had a few questions:
- Does it mean that we should first use "check_that" and then also use "assert_that" to make sure there is an abortTest exception and the test fails.
- I see that the tests fail even when the check_that condition fails.
- Is the difference between the two only about logging it to the report? 
Please clarify, thank you. 
Also let me know if I should be putting up questions on Google group or this is the right place?

**Comment by ndelon** [comment]
1. if you want to have a log of the check whatever the result is and to stop the test if the check is not successful, then you must use `require_that`
2. that's right
3. `check_that` logs the result whatever the result is and don't stop the test VS `assert_that` follows the `assert` semantic, meaning that it only logs and stop the test if the assertion is not successful

You can ask questions here, that's ok.

Regards.
