### ISSUE TITLE
lcc run skips execution of tests inside a folder created within the suites directory

### ISSUE THREAD

**Issue by kanchan04katare** [lemoncheesecake/lemoncheesecake#11]
I am using LCC framework, I have created different folder inside test suite.. but for some reason , the test file present inside the folder is not running by `lcc run` command.  any one know, where I can provide the path for same ?
I tried to add path project.py.
```
project_dir = os.path.dirname(__file__)
project = Project(project_dir)
suites_dir=os.path.join(project_dir, "suites/**")
```
But its not working.
Added screenshot for reference.
<img width="637" alt="test_folder" src="https://user-images.githubusercontent.com/7577468/74725505-fbebdc80-5263-11ea-939a-f26debe8ea81.png">

**Comment by ndelon** [comment]
Hello,

Could you provide more insights about the issue you encounter ? I don't understand from your message if nothing run at all, or if only some suites are not recognized (the output of "lcc show" for instance would be helpful). Here are some issues I can already see:
-  your `suites_dir=...` line in the project.py won't do anything, the only variable that is used from the project.py file in the "project" variable
- your "suites" directory must not contain an `__init__.py` file, it's not a Python package
- if your "test_sell_solutions_pages" directory is supposed to contain sub-suites then you must have a corresponding "test_sell_solutions_pages.py" file at the same level

Did you read http://docs.lemoncheesecake.io/en/latest/tests-and-suites.html ?

Regards.

**Comment by kanchan04katare** [comment]
Hi , Problem is test files present under suites directory is running fine . But the test files which are present under `test_sell_solution_pages` directory are not running.

I need to write test files for multiple pages,  for  that I am planning to create different folder under suites directory & run the files from there. 

In `lcc show` the test file present under `test_sell_solution_pages` directory are not shown.

Added screenshot for reference.
1) lcc show : 
<img width="607" alt="lcc_show" src="https://user-images.githubusercontent.com/7577468/74803521-2fca0f00-5303-11ea-83cd-58a1f57e5cb7.png">

2) test file present under directory in suites.
<img width="430" alt="inside_foler" src="https://user-images.githubusercontent.com/7577468/74803547-55571880-5303-11ea-897b-4c1785be7eb5.png">

**Comment by ndelon** [comment]
Hello,

Ok, in that case, like I told you in my first answer: _if your "test_sell_solutions_pages" directory is supposed to contain sub-suites then you must have a corresponding "test_sell_solutions_pages.py" file at the same level_ (as explained in http://docs.lemoncheesecake.io/en/latest/tests-and-suites.html, look for "as a module in a sub directory....").

Regards.

**Comment by kanchan04katare** [comment]
Thank you so much @ndelon !! appreciate the help.

**Comment by ndelon** [comment]
You're welcome.
