### ISSUE TITLE
Unable to view html reports when integrated with Jenkins

### ISSUE THREAD

**Issue by anarang** [lemoncheesecake/lemoncheesecake#13]
Hi,

I archived the build artifacts as 'report.html' and 'report.js' after running the tests on Jenkins. So, I am trying to run the tests on a docker container and then I archive the two files in Jenkins workspace. When I try to click on the link which reads report.html, it does not pick up the content from report.js and display the required results. This is what it looks like:
report.html -> shows a blank page
report.js -> shows the expected json output.
But, on local machine when we open the report.html in a browser it picks up the values from json and shows the relevant report.
Can you share if there is a way that html report needs to be generated so that jenkins displays them normally and also is able to publish it using the "Publish HTML report" plugin.

x-special/nautilus-clipboard
copy
file:///home/anarang/Pictures/Screenshot%20from%202020-03-24%2000-44-55.png

x-special/nautilus-clipboard
copy
file:///home/anarang/Pictures/Screenshot%20from%202020-03-24%2000-51-50.png

**Comment by ndelon** [comment]
Hello,

I think that you miss the `.html` (that contains all the HTML/JS/CSS resources used to build the report) sub directory, see:
```
$ lcc run
=================================== github ====================================
 OK  1 # github.organization                                                  

Statistics :
 * Duration: 0.279s
 * Tests: 1
 * Successes: 1 (100%)
 * Failures: 0

$ ls -la report/
total 24
drwxrwxr-x 3 nicolas nicolas 4096 Mar 23 23:58 .
drwxrwxr-x 7 nicolas nicolas 4096 Mar 23 23:58 ..
drwxrwxr-x 3 nicolas nicolas 4096 Mar 23 23:58 .html
-rw-rw-r-- 1 nicolas nicolas  592 Mar 23 23:58 report.html
-rw-rw-r-- 1 nicolas nicolas 5645 Mar 23 23:58 report.js
```
Please note that you will also have an `attachements` sub directory if you are logging attachments in your tests.

In fact, it's a better idea to copy the whole "report" parent directory to be sure that you will have all the necessary files needed by the HTML report, no matter how it is organized or how it will evolve in future versions of lemoncheesecake.

Regards.

**Comment by anarang** [comment]
yeah, I figured out the same right after I asked this question. Thanks. :)
