### ISSUE TITLE
Is there a env variable that can fetch the name of the current test?

### ISSUE THREAD

**Issue by anarang** [lemoncheesecake/lemoncheesecake#14]
Hi,
I am looking for an env variable that can print the name of the current test, like this:
test_create_product.create_product_blank_name

I tried lcc.test.__name__ but that doesn't seem to be working.

I am looking at using that while creating the filename for screenshots for a particular test as below:
name = $current_test_name
now = datetime.datetime.now().strftime('%Y-%m-%d_%H-%M-%S')
filename_ss = name + now

Looking forward to your help. 

Thanks :)

**Comment by ndelon** [comment]
Hello,

From what "context" do you want to do this ? From the `teardown_test` hook (see your previous question #12) ?
Simply `test.name` in that case (and `test.path` for the full test's path).

Regards.

**Comment by anarang** [comment]
is there a way to print the current test name outside the context of teardown_test?

**Comment by ndelon** [comment]
No, there is no way to get the current test from anywhere.

**Comment by anarang** [comment]
hmm okay, I thought there would be some environment variable that can be used. Though I tried looking in the source code but unable to find a way, I see the there are references to test name but not really usable. 
Thanks for your reply. :)
