### ISSUE TITLE
lcc run --exit-error-on-failure doesn't exit nonzero on failure in teardown_suite

### ISSUE THREAD

**Issue by chriswatrous** [lemoncheesecake/lemoncheesecake#15]
### Versions
MacOS 10.15.3
Python 3.6.4
lemoncheesecake  1.4.5

### To Reproduce
```
lcc bootstrap somedir
```

create file suites/demo.py:
```
import lemoncheesecake.api as lcc

@lcc.suite('Demo')
class demo:
    def teardown_suite(self):
        raise RuntimeError('🤮')

    @lcc.test('something')
    def something(self):
        pass
```

run with
```
lcc run --exit-error-on-failure; echo $?
```

### Expected Behavior

nonzero exit code and some indication that the teardown failed

### Actual Behavior
```
==================================== demo =====================================
 OK  1 # demo.something

Statistics :
 * Duration: 0.004s
 * Tests: 1
 * Successes: 1 (100%)
 * Failures: 0

0
```

The failure only shows up in the html report:
```
Caught unexpected exception while running test: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/lemoncheesecake/runner.py", line 87, in run_teardown_funcs
    teardown_func()
  File "/Users/chris/projects/other/lcc-bug/suites/demo.py", line 6, in teardown_suite
    raise RuntimeError('🤮')
RuntimeError: 🤮
```

**Comment by ndelon** [comment]
Hello,

This is currently the expected behavior in fact. A zero exit code is returned when all tests are successful, which is the case here (also see http://docs.lemoncheesecake.io/en/latest/cli.html#cmdoption-exit-error-on-failure).
But I guess that the current behavior and what you expect can be both argued.

Regards.

**Comment by chriswatrous** [comment]
It would be nice if there were an option to fail on teardown failure. I definitely need to know of my cleanup actions failed. Right now I'm doing this:
```
if grep '"failed"' report/report.js &> /dev/null; then
    echo 'Failure detected in test report (probably teardown_suite).'
    exit 1
fi
```

**Comment by ndelon** [comment]
I understand your need. I will think about it and I'll keep you informed.

**Comment by chriswatrous** [comment]
Thanks.

**Comment by ndelon** [comment]
@chriswatrous : the behavior of `--exit-error-on-failure` has been updated to include setup/teardown results.

Regards.

**Comment by ndelon** [comment]
I forgot to say: in the latest 1.4.7 release.

**Comment by chriswatrous** [comment]
Thanks a lot! It's working for me.
