### ISSUE TITLE
setup_test and teardown_test don't run when defined in outer class

### ISSUE THREAD

**Issue by chriswatrous** [lemoncheesecake/lemoncheesecake#17]
I'm not sure what the intended behavior for this but it would be nice to be able to define setup_test and teardown_test methods that run for all tests in a suite including tests defined in inner classes.

### Versions
MacOS 10.15.3
Python 3.7.7
lemoncheesecake  1.5.0

### To Reproduce
```
lcc bootstrap somedir
```

create file suites/demo.py:
```
import lemoncheesecake.api as lcc

@lcc.suite('Demo')
class demo:
    def setup_test(self, test):
        lcc.log_info('outer setup_test')

    def teardown_test(self, test, status):
        lcc.log_info('outer teardown_test')

    @lcc.suite('inner')
    class inner:
        def setup_test(self, test):
            lcc.log_info('inner setup_test')

        def teardown_test(self, test, status):
            lcc.log_info('inner teardown_test')

        @lcc.test('something')
        def something(self):
            pass
```

run with
```
lcc run
```

### Expected Behavior

Both the inner and outer setup_test and teardown_test methods should run.

### Actual Behavior

Only the inner setup_test and teardown_test methods run.

![Screen Shot 2020-08-04 at 4 04 50 PM](https://user-images.githubusercontent.com/9014937/89345219-b03fba80-d66c-11ea-9ed8-1aeab40f3199.png)

**Comment by chriswatrous** [comment]
same behavior with lemoncheesecake 1.5.2

**Comment by chriswatrous** [comment]
Related problem:
```
import lemoncheesecake.api as lcc

@lcc.suite('Demo')
class demo:
    def setup_suite(self):
        lcc.log_info('outer setup_suite')

    def teardown_suite(self):
        lcc.log_info('outer teardown_suite')

    @lcc.suite('inner')
    class inner:
        def setup_suite(self):
            lcc.log_info('inner setup_suite')

        def teardown_suite(self):
            lcc.log_info('inner teardown_suite')

        @lcc.test('something')
        def something(self):
            pass
```

### Expected

Both the inner and outer setup_suite and teardown_suite methods should run.

### Actual

Only the inner ones run.

**Comment by ndelon** [comment]
Hello,

This is not something clearly expressed in the documentation but this is the expected behavior: a suite does not "inherit" the setup/teardown hooks of its parent suites, no matter how test suites are nested (sub-classes, modules in sub-directories, etc...).

Regards,

Nicolas.
