### ISSUE TITLE
common package

### ISSUE THREAD

**Issue by JulianToledano** [lemoncheesecake/lemoncheesecake#19]
Hi guys 👋,

Is there a way (or I'm doing something wrong) to have a common package with methods that different suites or tests can use. For example create a randomized payload.

My current set up is as follows:
```
.
├── common
│   ├── utils.py
│   └──__init__.py
├── fixtures
├── input_data
├── project.py
└── suites
```
but a ModuleNotFoundError occurs while importing the package. I also tried moving common to suites directory and making the import in Project pre_run() but both fails. My current workaround is a symlink to the venv.

Is there a way to achieve this or is it impossible?

**Comment by anarang** [comment]
Hi, you can try exporting PYTHONPATH, that might help.
```
$pwd
/path/to/lcc_tests

$export PYTHONPATH=/path/to/lcc_tests
```
thanks. :)

**Comment by ndelon** [comment]
Hello,

A solution would be to change your `sys.path` from the `project.py` file. If you have a default `project.py` such as this:
```python
import os.path

from lemoncheesecake.project import Project


project_dir = os.path.dirname(__file__)
project = Project(project_dir)
```

you can turn it into this:
```python
import os.path
import sys

from lemoncheesecake.project import Project


project_dir = os.path.dirname(__file__)
sys.path.append(project_dir)
project = Project(project_dir)
```

Regards.

**Comment by JulianToledano** [comment]
> 
> 
> Hello,
> 
> A solution would be to change your `sys.path` from the `project.py` file. If you have a default `project.py` such as this:
> 
> ```python
> import os.path
> 
> from lemoncheesecake.project import Project
> 
> 
> project_dir = os.path.dirname(__file__)
> project = Project(project_dir)
> ```
> 
> you can turn it into this:
> 
> ```python
> import os.path
> import sys
> 
> from lemoncheesecake.project import Project
> 
> 
> project_dir = os.path.dirname(__file__)
> sys.path.append(project_dir)
> project = Project(project_dir)
> ```
> 
> Regards.

That works like a charm. Thanks!
