### ISSUE TITLE
installed on new mac with pip doesn't find the lcc command

### ISSUE THREAD

**Issue by jpita** [lemoncheesecake/lemoncheesecake#2]
Hi,

just moved to a brand new mac and, after installing with pip, it says it doesn't know the command.
any ideas?

**Comment by ndelon** [comment]
Hello @jpita ,

What version of pip are you using ? With a "recent" version of pip, it should be installed in /usr/local/bin/ and be accessible if /usr/local/bin is in your $PATH.

**Comment by ndelon** [comment]
Hello @jpita ,

Did you solve your installation issue ?

**Comment by ndelon** [comment]
Hello @jpita ,

I close the ticket. Feel free to reopened it if needed.

**Comment by jpita** [comment]
Hi @ndelon ,

I add some issues with `__init-py__` and importing files with lcc and was able to do it using the same code with pytest, so, due to time constraints to implement my solution I went on with pytest.

I'll try to revisit lcc at a later stage

thanks

**Comment by ndelon** [comment]
Hello @jpita ,

If you have some time, I really like to have more information about the issue you get so that I can help you. 

Regards,
