### ISSUE TITLE
Getting "Connection pool is full, discarding connection: 127.0.0.1" error while running test cases on thread

### ISSUE THREAD

**Issue by ShreyaAsthana** [lemoncheesecake/lemoncheesecake#21]
Hi,

I am trying to run my lcc test cases in parallel so as to minimize execution time of test suites. When I am hitting command "lcc run --thread 5" then it is showing me "Connection pool is full, discarding connection: 127.0.0.1" after 3-4 test case. 
I thought I should decrease no of thread then I put it as "lcc run --thread 2" but still I am getting same connection pool error.
My test cases are running on same web browser instance and on single web browser which is causing one more issue when I am using threading on my test suites. Issue arise here is one thread is trying to execute one test case and before completion of this running test case another thread starting execution of another test case which leads to failure of 1st running test case. 
Is there any other way to minimize test execute time? Is @lcc.Thread will help in this as I have not used @lcc.thread in my test suite yet?

**_fixture.py file_**
@lcc.fixture(names=("driver", "driver_obj"), scope="session")
def setup():
    lcc.log_info("Initialising the webdriver object, opening the browser...")
    # Initialise the global webdriver, open the browser and maximise the
    # browser window

    if headless == "yes":
        options = Options()
        options.add_argument('--headless')
        options.add_argument("window-size=1920,1080 ")
        options.add_argument('--no-sandbox')

        driver = webdriver.Chrome(
            ChromeDriverManager().install(),
            chrome_options=options)
        logging.info(
            "Chrome driver has been initialised successfully in headless mode")
    else:
        driver = webdriver.Chrome(ChromeDriverManager().install())
        #caps = DesiredCapabilities.FIREFOX.copy()
        #driver = webdriver.Firefox(executable_path=GeckoDriverManager().install(), capabilities=caps)
        logging.info("Chrome driver has been initialised successfully")

    driver.implicitly_wait(15)
    driver.maximize_window()
    driver.implicitly_wait(10)

    driver.get(url)
    print(url)
    # the global driver object can be used globally in the tests.
    yield driver
    lcc.log_info("Closing the browser window...")
    driver.close()
    driver.quit()

**Comment by ndelon** [comment]
Hello,

The issue here is that multiple tests running in parallel share a single instance of browser, it cannot work.

You have to have a single browser at a time a per thread, meaning the scope of the fixture cannot be "session", it must be "test".

Please note that a new browser will be spawned and destroyed for each test, in other words it will slow down a bit the test run.

Regards,

Nicolas.

**Comment by ShreyaAsthana** [comment]
Thanks for your suggestion. I think problem will not going to resolve if it will increase execution time as my aim is to decrease execution time.
Also, do you have any idea why connection pool error is coming when I am using thread to running lcc test suites?

**Comment by ndelon** [comment]
From your initial message, I did not understand where this "connection pool" error message is coming from.. Can you more provide more details ?

**Comment by ShreyaAsthana** [comment]
When I am running command lcc run -- thread 2 then this connection pool is full error is coming.
I have not added anything related to threading in test cases. Just running my test case with command lcc run -- thread 2.

**Comment by ndelon** [comment]
I still don't get where the error message appear, do you have a more complete stacktrace ?

**Comment by ShreyaAsthana** [comment]
Here is the screenshot of what I have written in terminal. After writing "lcc run --thread 2" , it is running few test cases in parallel and then giving "Connection pool is full". Do you have any idea why this is occuring?

![image](https://user-images.githubusercontent.com/72568052/130563808-fc61efdb-afaa-44e3-a443-7e84b82aae2e.png)

**Comment by ndelon** [comment]
The error messages seem to come from Selenium. If they appear only when you are running tests with 2 threads or more, I guess this is side effect of sharing a single browser between multiple threads.

**Comment by ShreyaAsthana** [comment]
I tried running on multiple browser but same connection pool error is throwing.

**Comment by ShreyaAsthana** [comment]
I tried changing scope to "suite" and then tried to run command "lcc run --thread 2" but still getting "connection pool" error.
![image](https://user-images.githubusercontent.com/72568052/130618742-2ef42788-9333-4614-8035-9706943dec37.png)
![image](https://user-images.githubusercontent.com/72568052/130618912-f469081a-8eee-46fc-9173-8a4279c59873.png)

**Comment by ndelon** [comment]
As I said previously, the fixture must have the **"test"** scope so that it won't be shared by two tests at the same time.

**Comment by ShreyaAsthana** [comment]
I completely agree with your suggestion but my test cases are dependent to each other that is why I can not run my test on "test" scope.
I have used @lcc.depends_on to maintain dependency between test cases.

**Comment by ndelon** [comment]
Well, this is not really a good practice to have dependent tests, but in this case, it means that those tests could not have been parallelized anyway.

**Comment by ShreyaAsthana** [comment]
Thanks @ndelon for your suggestion!!! :)

**Comment by ndelon** [comment]
Hello,

I just released the 1.9.0 version (https://github.com/lemoncheesecake/lemoncheesecake/blob/master/CHANGELOG.md#190-2021-09-05) with a new feature that solve the problematic you described in your initial message.

The per-thead fixture feature (http://docs.lemoncheesecake.io/en/latest/fixtures.html#per-thread-fixtures) allows you to share an object on a per-thread basis.

To make it short, if you change:
```python
@lcc.fixture(names=("driver", "driver_obj"), scope="session")
```

for:
```python
@lcc.fixture(names=("driver", "driver_obj"), scope="session", per_thread=True)
```

It should do the trick.

Regards,

Nicolas.

**Comment by shisri** [comment]
Hi Nicolas,

Thanks for the update on release part. I tried adding argument "per_thread=True" but it is not allowing me to add this argument Saying as "Unexpected Argument". I am using lemoncheesecake version 1.9.0 (using Python 3.6.8).

**Comment by ShreyaAsthana** [comment]
Hi Nicolas,

Thanks for the update on release part. I tried adding argument "per_thread=True" but it is not allowing me to add this argument Saying as "Unexpected Argument". I am using lemoncheesecake version 1.9.0 (using Python 3.6.8).
![image](https://user-images.githubusercontent.com/72568052/132165540-5f588025-d4ed-4cd2-9992-53f176b43489.png)
![image](https://user-images.githubusercontent.com/72568052/132165585-ae3cb5eb-a742-4249-b0d9-e234b3e8e6da.png)

**Comment by ndelon** [comment]
I guess you have not installed the 1.9.0 version in the (virtual) environment of your IDE.
Does it work from the command line (`lcc run`) where your did your `pip install` ?

**Comment by ShreyaAsthana** [comment]
I have entered command lcc run from command line and it is showing me "Suite 'test_sample' uses per-thread fixture 'driver_obj' which is not allowed".

**Comment by ShreyaAsthana** [comment]
Hi Nicolas,
I am able to resolve IDE issue. Virtal env was not set up correctly in IDE. But still when I am doing lcc run , same above error is showing. "Suite 'test_sample' uses per-thread fixture 'driver_obj' which is not allowed".
**test.py**
```
@lcc.suite("parallel test", rank=1)
class parallel_test(Screenshot):
    driver = lcc.inject_fixture("driver_object")

    @lcc.test("Create parallel test")
    def create_parallel_test(self):
        url = fixture.url 
        self.driver.get(url)
```

**Comment by ShreyaAsthana** [comment]
Above issue is resolved after changing **test.py** as :
```
@lcc.suite("parallel test", rank=1)
class parallel_test(Screenshot):

    @lcc.test("Create parallel test")
    def create_parallel_test(self, driver):
        url = fixture.url 
        driver.get(url)

```
As mentioned in release note that inspite of "session" as scope fixture, it work at test level. 
But now I come up with another error. I hit command "lcc run <suite_path> --thread 2. It ran 2 test cases but as soon as it completes 2 test cases on 2 different browser, it gave me below error:
```
Traceback (most recent call last):
  File "/home/xyz/Documents/project_name/env/bin/lcc", line 11, in <module>
    load_entry_point('lemoncheesecake==1.9.0', 'console_scripts', 'lcc')()
  File "/home/xyz/Documents/project_name/env/lib64/python3.6/site-packages/lemoncheesecake/cli/main.py", line 53, in main
    return command.run_cmd(cli_args)
  File "/home/xyz/Documents/project_name/env/lib64/python3.6/site-packages/lemoncheesecake/cli/commands/run.py", line 181, in run_cmd
    return run_suites_from_project(load_project(cli_args.project), cli_args)
  File "/home/xyz/Documents/project_name/env/lib64/python3.6/site-packages/lemoncheesecake/cli/commands/run.py", line 108, in run_suites_from_project
    cli_args.force_disabled, cli_args.stop_on_failure, nb_threads
  File "/home/xyz/Documents/project_name/env/lib64/python3.6/site-packages/lemoncheesecake/project.py", line 263, in run_project
    nb_threads=nb_threads
  File "/home/xyz/Documents/project_name/env/lib64/python3.6/site-packages/lemoncheesecake/runner.py", line 589, in run_suites
    force_disabled=force_disabled, stop_on_failure=stop_on_failure, nb_threads=nb_threads
  File "/home/xyz/Documents/project_name/env/lib64/python3.6/site-packages/lemoncheesecake/runner.py", line 564, in _run_suites
    raise exception.__class__(serialized_exception)
AttributeError: 
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
Traceback (most recent call last):
  File "/home/xyz/Documents/project_name/env/lib64/python3.6/site-packages/lemoncheesecake/events.py", line 125, in _handler_loop
    self.handle_event(event)
  File "/home/xyz/Documents/project_name/env/lib64/python3.6/site-packages/lemoncheesecake/events.py", line 98, in handle_event
    self._event_types[event.__class__.get_name()].handle(event)
  File "/home/xyz/Documents/project_name/env/lib64/python3.6/site-packages/lemoncheesecake/events.py", line 44, in handle
    handler(event)
  File "/home/xyz/Documents/project_name/env/lib64/python3.6/site-packages/lemoncheesecake/reporting/writer.py", line 145, in on_log
    Log(event.log_level, event.log_message, event.time), event
  File "/home/xyz/Documents/project_name/env/lib64/python3.6/site-packages/lemoncheesecake/reporting/writer.py", line 26, in _add_step_log
    assert not step.end_time, "Cannot update step '%s', it is already ended" % step.description
AttributeError: 'NoneType' object has no attribute 'end_time'
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

```

**Comment by ndelon** [comment]
Hello @ShreyaAsthana ,

That's a bug, thanks for pointing this out. It happens when creating logs in the setup phase of a per-thread fixture.

It has been fixed in the 1.9.1 release.

Thanks again for the report.

Regards,

Nicolas.

**Comment by ShreyaAsthana** [comment]
Most welcome Nicolas. :) May I know when we are expecting 1.9.1 release?

**Comment by ndelon** [comment]
Hello,

As indicated in my previous message, the 1.9.1 was released 4 days ago.

Regards.

**Comment by ShreyaAsthana** [comment]
Thanks @ndelon :)
