### ISSUE TITLE
error: "AttributeError: 'InjectedFixture' object has no attribute 'get'"

### ISSUE THREAD

**Issue by shisri** [lemoncheesecake/lemoncheesecake#22]
Hi, 
When I am trying to run my lcc test suites through command "lcc run", it is showing me Attribute Error " AttributeError: 'InjectedFixture' object has no attribute 'get".

**Fixture.py**
```
@lcc.fixture(names=("driver", "driver_object"), scope="test")
def setup():
    lcc.log_info("Initialising the webdriver object, opening the browser...")

    if headless == "yes":
        options = Options()
        options.add_argument('--headless')
        options.add_argument("window-size=1920,1080 ")
        options.add_argument('--no-sandbox')

        driver = webdriver.Chrome(
            ChromeDriverManager().install(),
            chrome_options=options)
        logging.info(
            "Chrome driver has been initialised successfully in headless mode")
    else:
        driver = webdriver.Chrome(ChromeDriverManager().install())
        logging.info("Chrome driver has been initialised successfully")

    driver.implicitly_wait(15)
    driver.maximize_window()
    driver.implicitly_wait(10)
    driver.get(url)
    print(url)
    yield driver
    driver.close()
    driver.quit()

```

**test.py**
```
@lcc.suite("Sample test", rank=1)
class sample_test(Screenshot):
    driver = lcc.inject_fixture("driver_object")

    @lcc.test("Create sample test")
    def create_sample_test(self):
        url = fixture.url 
        self.driver.get(url)
```

**Comment by ndelon** [comment]
Hello,

Are you sure that the code you show corresponds to the error ?
The fixture you defined has incompatible: it should be "suite" (or "session") but not "test" and it should show you an explicit error message.
What lemoncheesecake version do you use ?

Regards,

Nicolas.

**Comment by shisri** [comment]
Hi ndelon,

I am using lcc version 1.8.0 . I want to run my test cases on "test" level scope. Sorry my bad. Actual error it is showing is : " Suite 'drupal_test.drupal_edit_layout' uses fixture 'driver_obj' which has an incompatible scope" . 
Can you please suggest me how I can run my lcc suites on "test" level scope?

**Comment by ndelon** [comment]
When you inject a fixture into a **test suite** (that's what you do with `lcc.inject_fixture()`, it must have a scope greater or equal to "**suite**" (that is pretty logical). Then you have two choices:
- if you want your browser being shared between tests, use the "suite" scope for the fixture
- if you want one browser per test, then keep the "test" scope, but do not use `lcc.inject_fixture()` instead, you must pass the fixture directly as argument to the test functions/methods

Regards,

Nicolas.

**Comment by shisri** [comment]
Thanks Nicolas, can you please give me some sample code example just to make it more clear on second point about passing ficture directly as argument to test methods?

**Comment by ndelon** [comment]
```python
@lcc.suite("Sample test", rank=1)
class sample_test(Screenshot):
    @lcc.test("Create sample test")
    def create_sample_test(self, driver):
        driver.get(url)
```

More details on http://docs.lemoncheesecake.io/en/latest/fixtures.html

**Comment by shisri** [comment]
Hi Nicolas, 
I tried doing same way but this time I am getting "AttributeError: 'sample_test' object has no attribute 'get' " . Do I need to change anything else inside fixture file? 
**Fixture file:**
```
@lcc.fixture(scope="pre_run")
def setup_test_repo():
    try:
        os.mkdir('screenshots')
        os.chdir('screenshots')
    except subprocess.CalledProcessError as e:
        logging.info(
            "Test setup did not complete successfully'")
        raise e


@lcc.fixture(names=("driver", "driver_object"), scope="test")
def setup():
    lcc.log_info("Initialising the webdriver object, opening the browser...")

    if headless == "yes":
        options = Options()
        options.add_argument('--headless')
        options.add_argument('--no-sandbox')

        driver = webdriver.Chrome(
            ChromeDriverManager().install(),
            chrome_options=options)
        logging.info(
            "Chrome driver has been initialised successfully in headless mode")
    else:
        driver = webdriver.Chrome(ChromeDriverManager().install())
        logging.info("Chrome driver initialised successfully")

    driver.maximize_window()

    driver.get(url)
    yield driver
    driver.close()
    driver.quit()


```

**Comment by ndelon** [comment]
Can you show me the code of this test ?

**Comment by shisri** [comment]
```
@lcc.suite("Tests suite", rank=1)
class sample_test(Screenshot):
    @lcc.test("Test xyz")
    def test_xyz(driver):
        url = fixture.url + "abc"
        driver.get(url)
```

This is my test file

**Comment by ndelon** [comment]
The `self` argument is missing:
```python
def test_xyz(self, driver):
    [...]
```

**Comment by shisri** [comment]
Thanks for the help Nicolas, it worked. Initially my test suites was running at "session" scope and I am used class for each test suite. Also, I have created one base_screenshot class and I am inheriting this class in every suite classes. After changing scope from suite to test error is coming in base_screenshot class as "AttributeError: 'NoneType' object has no attribute 'save_screenshot' " . 
**base_screenshot.py**
```
class Screenshot:
    driver = lcc.inject_fixture("driver_obj")

    def teardown_test(self, test, status):
        if status == "passed":
            pass
        elif status == "failed":
            lcc.log_info("failure was observed in the test...")
            test_name = test.name
            now = datetime.datetime.now().strftime('%Y-%m-%d_%H-%M-%S')
            screenshot_filename = test_name + now + ".png"
            self.driver.save_screenshot(screenshot_filename)
            lcc.save_attachment_file(screenshot_filename)
            os.remove(screenshot_filename)
        else:
            lcc.log_info("unable to capture a screenshot.")
```

**sample_test.py**
```
@lcc.suite("Tests suite", rank=1)
class sample_test(Screenshot):
    @lcc.test("Test xyz")
    def test_xyz(self, driver):
        url = fixture.url + "abc"
        driver.get(url)
```

**Comment by ndelon** [comment]
If you're doing:
```python
driver = lcc.inject_fixture("driver_obj")
```
with `driver_obj` being a fixture with the scope "test" it should normally raise an error about fixture scope incompatibility (see previous comment https://github.com/lemoncheesecake/lemoncheesecake/issues/22#issuecomment-911567267)

So, regarding `teardown_test` it cannot work that way. I recommend you to make the proper error handling in the test explicitly.

**Comment by shisri** [comment]
Is there any other way that we can take screenshot when scope is "test" inspite of doing error handling in each test explicitly?

**Comment by ndelon** [comment]
I think that it is better practice to handle error where it happens to give more context about the error in the report.

Otherwise, if you read my https://github.com/lemoncheesecake/lemoncheesecake/issues/22#issuecomment-911567267 previous message, you could also use a suite or session-scoped fixture that will do the trick if your tests aim to be run sequentially. If you want your tests to be parallelizable, then the upcoming 1.9.0 lemoncheesecake release should ease that.

Independently from the sequential/parallelizable topic, I would repeat what I've said in the beginning of this message: it is not a good testing practice to do what is done in your `teardown_test` method. I recommend you to handle errors where they happen.

**Comment by shisri** [comment]
My main aim to run test in parallel so that I can decrease execution time that is why I am trying to make fixture as test-scoped. Do you have any idea about when 1.9.0 lcc is releasing and also how it is gonna solve my parallel execution issue?
On topic "handling error in tests", I agree you on this point. I can handle error at test level but this will show up in report and I want to take screenshot as well when such error occur inside any tests. Will that solve my purpose of taking screenshot?

**Comment by ndelon** [comment]
The 1.9.0 will be (mainly) about sharing object in tests running on the same thread, it will be release in the very next few days.

The test "fails" after a specific action of yours, when this happens you can handle the case and take a screenshot.

**Comment by ndelon** [comment]
Hello,

The 1.9.0 has just been released and brings per-thread object sharing feature. I invite you to read:
- http://docs.lemoncheesecake.io/en/latest/fixtures.html#per-thread-fixtures
- and http://docs.lemoncheesecake.io/en/latest/parallelism.html#threaded-factory

As I said in my previous messages, I encourage you to implement a more accurate error handling instead of a catch-all method and to use a per-thread fixture (see my first link).

Otherwise, the solution described in second link should do the trick.

Regards,

Nicolas.

**Comment by shisri** [comment]
Thanks Nicolas. Lets say I am opting to make my test case parallelized  through "ThreadedFactory" not through "per_thread fixture" then will it work on test-scoped fixture?
Referencing my above shared fixture code, do I need to make any changes to fixture if I want to user "ThreadFactory" with test-scoped fixture?

**Comment by ndelon** [comment]
If you're using the `ThreadedFactory` over a per-thread fixture for your web driver, then you are not using a fixture, that's the point.
Just take a look at the example in http://docs.lemoncheesecake.io/en/latest/parallelism.html#threaded-factory which I think is self-explanatory.

**Comment by ndelon** [comment]
I close this ticket, fell free to re-open it if you still have questions on that topic @shisri .
