### ISSUE TITLE
Is there any way to capture screenshot for fail test cases if my fixture is using scope as "session" and "per_thread=True"?

### ISSUE THREAD

**Issue by ShreyaAsthana** [lemoncheesecake/lemoncheesecake#23]
Hi,
I wanted to know is there any way that I can capture screenshot of fail test cases if I am using "per_thread" mechanism and also fixture is having scope as "session"?

**Comment by ndelon** [comment]
Hello,

I guess you're talking about selenium. There is no particularity if you use per-thread fixtures.
When something unexpected happens (for instance: you get a WebDriverException exception), take a screenshot at that moment.

Regards.

Nicolas.

**Comment by ShreyaAsthana** [comment]
I have create one base_screenshot class and extending this class inside my suite class. But now that I am using per_thread this is not working and throwing error as "'NoneType' object has no attribute 'save_screenshot'".

**base_screenshot.py**
```
class Screenshot:
    driver = None

    def teardown_test(self, test, status):
        if status == "passed":
            pass
        elif status == "failed":
            lcc.log_info("Please find the screenshot below as a failure was observed in the test...")
            test_name = test.name
            now = datetime.datetime.now().strftime('%Y-%m-%d_%H-%M-%S')
            screenshot_filename = test_name + now + ".png"
            self.driver.save_screenshot(screenshot_filename)
            lcc.save_attachment_file(screenshot_filename)
            os.remove(screenshot_filename)
        else:
            lcc.log_info("Status of the test not known and unable to capture a screenshot.")
```

**fixture.py**
```
@lcc.fixture(scope="pre_run")
def setup_test_repo():
    try:
        os.mkdir('screenshots')
        os.chdir('screenshots')
    except subprocess.CalledProcessError as e:
        logging.info(
            "Test setup did not complete successfully, error encountered during 'pantheon push'")
        raise e
```

Do you have any suggestion how to fix this?

**test.py**
```
@lcc.suite(" Login test", rank=1)
class test_login(Screenshot):

    @lcc.test("Should navigate users to login page")
    def test_user_should_navigate_to_login_page(self, driver):
        url = fixture.url
        driver.get(url)
```

**Comment by ndelon** [comment]
As described in a previous ticket (https://github.com/lemoncheesecake/lemoncheesecake/issues/22#issuecomment-913010630), I don't consider handling error in the `teardown_test` method a good programming practice.

However, if you absolutely want to this, you need to be able to access the driver instance from the `teardown_test` method, which is not possible with a test-scoped fixture. Instead, you should use a `ThreadedFactory` to instantiate your drivers (see a concrete example here: http://docs.lemoncheesecake.io/en/latest/parallelism.html#creating-objects-on-a-per-thread-basis).
This is more low-level than a per-thread fixture so it provides more flexibility while being more complex to use.

Just a note about the way you're doing your screenshots, it seems to me overly complex, you just have to do something like this:
```python
with lcc.prepare_attachment("screenshot.png", "Screenshot") as path:
    self.driver.save_screenshot(path)
```

You don't need the `setup_test_repo` fixture, the datetime stuff, etc...

**Comment by ShreyaAsthana** [comment]
Thanks @ndelon for suggesting me this. If I will use "ThreadedFactory" then I have to instantiate in every test.py file right?

**Comment by ndelon** [comment]
I don't know what you mean by "instantiate" here, but you could implement the all driver instantiation mechanism in a base class and then inherit this class in your actual suite classes.

**Comment by ShreyaAsthana** [comment]
I got you. So after doing this, I can inherit "base_screenshot" in actual suite class to capture screenshot of failed test case right?

**Comment by ndelon** [comment]
Yes, and you can also implement your `teardown_test` method in the base class.

**Comment by ShreyaAsthana** [comment]
Thanks @ndelon , it worked for me. :)

**Comment by ShreyaAsthana** [comment]
After implementing ThreadedFactory, Chrome browser is getting invoked for every single test cases when I am hitting command lcc run --thread 5.
I want to invoke only 5 chrome browser. 
**base_threaded_factory.py**
```
class DriverFactory(lcc.ThreadedFactory):
    def setup_object(self):
        lcc.log_info("Initialising the webdriver object, opening the browser...")
        # Initialise the global webdriver, open the browser and maximise the
        # browser window
        if headless == "yes":
            options = Options()
            options.add_argument('--headless')
            options.add_argument("window-size=1920,1080 ")
            options.add_argument('--no-sandbox')
            driver = webdriver.Chrome(
                ChromeDriverManager().install(),
                chrome_options=options)
            logging.info(
                "Chrome driver has been initialised successfully in headless mode")
            driver.implicitly_wait(15)
            driver.maximize_window()
            driver.implicitly_wait(10)

        else:
            driver = webdriver.Chrome(ChromeDriverManager().install())
            # caps = DesiredCapabilities.FIREFOX.copy()
            # driver = webdriver.Firefox(executable_path=GeckoDriverManager().install(), capabilities=caps)
            logging.info("Chrome driver has been initialised successfully")
            driver.implicitly_wait(15)
            driver.maximize_window()
            driver.implicitly_wait(10)

        return driver

    def teardown_object(self, driver):
        driver.get(url)
        print(url)
        # the global driver object can be used globally in the tests.
        yield driver
        lcc.log_info("Closing the browser window...")
        driver.close()
        driver.quit()

```
**removed below code from fixture**
```
'''@lcc.fixture(names=("driver", "driver_obj"), scope="session", per_thread=True)
def setup():
    lcc.log_info("Initialising the webdriver object, opening the browser...")
    # Initialise the global webdriver, open the browser and maximise the
    # browser window

    if headless == "yes":
        options = Options()
        options.add_argument('--headless')
        options.add_argument("window-size=1920,1080 ")
        options.add_argument('--no-sandbox')

        driver = webdriver.Chrome(
            ChromeDriverManager().install(),
            chrome_options=options)
        logging.info(
            "Chrome driver has been initialised successfully in headless mode")
    else:
        driver = webdriver.Chrome(ChromeDriverManager().install())
        #caps = DesiredCapabilities.FIREFOX.copy()
        #driver = webdriver.Firefox(executable_path=GeckoDriverManager().install(), capabilities=caps)
        logging.info("Chrome driver has been initialised successfully")

    driver.implicitly_wait(15)
    driver.maximize_window()
    driver.implicitly_wait(10)

    driver.get(url)
    print(url)
    # the global driver object can be used globally in the tests.
    yield driver
    lcc.log_info("Closing the browser window...")
    driver.close()
    driver.quit()   '''
```
**test.py**
```
@lcc.suite(" Login test", rank=1)
class test_login(DriverFactory, Screenshot):
        def __init__(self):
        super().__init__()
        self.factory = DriverFactory()

    @property
    def driver(self):
        return self.factory.get_object()

    def teardown_suite(self):
        self.factory.teardown_factory()
    @lcc.test("Should navigate users to login page")
    def test_user_should_navigate_to_login_page(self):
        url = fixture.url
        self.driver.get(url)

```

**Comment by ndelon** [comment]
The browser "pool" is associated to each suite, it means that if you have multiple tests splited between multiple suites, you will have more than 5 browser spawned, I think that is the issue you encounter.

In that case, try the following changes:

First, create a `driver_factory` fixture:
```python
@lcc.fixture(scope="session")
def driver_factory():
    factory = DriverFactory()
    yield factory
    factory.teardown_factory()
``` 

Second, your test suite should look like this:
```python
@lcc.suite("Login test", rank=1)
class login_test(Screenshot):
    def setup_suite(self, driver_factory):
        self.driver_factory = driver_factory

    @property
    def driver(self):
        return self.driver_factory.get_object()
```

And then you can add your tests in the suite of course.

It must have the excepted behavior.

After that, I encourage you to rename your `Screenshot` class into something more generic (`SeleniumSuite` for instance) and then to extract the `setup_suite` and `driver` methods, move them into that base class, and inherit that base class wherever needed (in the final suite classes).

**Comment by ShreyaAsthana** [comment]
It worked!!.. Thanks @ndelon for suggestion :)

**Comment by ndelon** [comment]
Hello @ShreyaAsthana  ,

FYI lemoncheesecake-selenium (https://lemoncheesecake-selenium.readthedocs.io/en/latest/) has just been released and should help you with some of the problematic you raised in this ticket, among which "automatic screenshot on failure".

Regards,

Nicolas.
