### ISSUE TITLE
Having issue in Genrating xml, Junit Reports. Getting error `Unknown reporting backend`.

### ISSUE THREAD

**Issue by lyfofvipin** [lemoncheesecake/lemoncheesecake#24]
Hi,
I have some testes written in lcc and I want the xml/junit result format so that I can push them further.
I follow this doc to run the tests :
  http://docs.lemoncheesecake.io/en/latest/cli.html
But I am having some issues it's giving error:
`Unknown reporting backend`
Here  are the commands I tried:
```
(project_env) [vipikuma@kvy ]$ lcc run --reporting +xml
Unknown reporting backend 'xml'
(project_env) [vipikuma@kvy ]$ lcc run --reporting +junit
Unknown reporting backend 'junit'
(project_env) [vipikuma@kvy ]$ lcc --version
lemoncheesecake version 1.11.2 (using Python 3.9.7 - ....../project_env/bin/python3)
```
So can you help me with the same?

**Comment by ndelon** [comment]
Hello @vipin3699 ,

The "junit" backend requires special extra install like documented in http://docs.lemoncheesecake.io/en/latest/installation.html, meaning you should install lemoncheesecake like this:
```
$ pip install lemoncheesecake[junit]
```

Regards.

**Comment by lyfofvipin** [comment]
Acknowledged It worked for me ( I just install the package via requirements.txt of the project so missed this my bad ),
Thanks for the Quick response. :)
