### ISSUE TITLE
JUnit reporting not working with LCC

### ISSUE THREAD

**Issue by jain-neeeraj** [lemoncheesecake/lemoncheesecake#25]
I am trying to run a test with junit reporter but getting an error mentioning "unknown reporting backend junit"

I have tried command mentioned on the documentation page 
http://docs.lemoncheesecake.io/en/latest/cli.html#cmdoption-reporting

System information:
Python: 3.10.2
LCC: 1.12.0

![image](https://user-images.githubusercontent.com/31276396/157386208-9c97cd85-2543-46de-bc23-65f3e938403f.png)

**Comment by ndelon** [comment]
Hello,

I guess that lemoncheesecake has not been installed with the junit support, see http://docs.lemoncheesecake.io/en/latest/installation.html

Regards,

Nicolas.

**Comment by jain-neeeraj** [comment]
Yes, this solved the problem.
