### ISSUE TITLE
Order of tests is not preserved in the test report.

### ISSUE THREAD

**Issue by akshayamaldhure** [lemoncheesecake/lemoncheesecake#3]
I have defined a few tests in my suite with the suite being defined as a module. The tests are executed in a proper order, but they appear in a different order in the test report. It seems like the skipped tests are appearing first right after `setup_suite()`.

lemoncheesecake version: 0.19.3

**Comment by ndelon** [comment]
Hello @akshayamaldhure ,

I have reproduced an issue dealing with "error in setup_suite" + "skipped tests are no longer ordered in the report", something like this, I have a module with:
- a `setup_suite` function that raises an exception
- a test named `test_1`
- a test named `test_2`
- a test named `test_3`

In the generated HTML report, the setup_suite entry is marked as **FAILED**, test_1, test_2, test_3 are marked as **SKIPPED** but do NOT appear in that order.

Is that the issue you encounter ?

**Comment by akshayamaldhure** [comment]
In my case, the `setup_suite()` is passed, but the first test after it fails and it explicitly raises an `AbortSuite` exception. So rest of the tests in the suite except `teardown_suite()` are skipped.

**Comment by ndelon** [comment]
Ok, I see the issue. It will be fixed by the end of the week and I will keep you updated.

**Comment by ndelon** [comment]
The issue has been fixed in the 0.19.4 release. Thank for you pointing out this issue. 

Regards

**Comment by akshayamaldhure** [comment]
Thank you @ndelon.
