### ISSUE TITLE
Question: Async\await methods using in tests

### ISSUE THREAD

**Issue by yauheni-vasilyeu** [lemoncheesecake/lemoncheesecake#6]
Good time of the day!

I need to test python library with async/await functional api.
How i can write test in which async methods are use?

e.g. if I make 'setup' or 'teardown' functions asynchronous, test not run, because 'setup' function return coroutine object to lcc; I think with test functions it will be the same.

Maybe you can explain for me, how can I use awaitable objects in lcc tests.

Thanks in advance

**Comment by ndelon** [comment]
Hello @evgeniivas ,

Introduction: I am not a specialist of async/await ;-)

There should no be issue using coroutines in setup, teardown, test functions/methods BUT you have to make sure that everything started within a test (for instance) is also finished within that test: any code execution cannot continue while the test is supposed to be finished, it won't work.

Best regards,

Nicolas.

**Comment by yauheni-vasilyeu** [comment]
> Hello @evgeniivas ,
> 
> Introduction: I am not a specialist of async/await ;-)
> 
> There should no be issue using coroutines in setup, teardown, test functions/methods BUT you have to make sure that everything started within a test (for instance) is also finished within that test: any code execution cannot continue while the test is supposed to be finished, it won't work.
> 
> Best regards,
> 
> Nicolas.

thanks you for answer.

in python, await can used only in async functions => I need to make test functions async;
when I make these functions async, they not run

Maybe you can make some feature to run async tests?

**Comment by ndelon** [comment]
As I said previously, when you reach the end of the test function, all the coroutines ran by the test function have to be finished, otherwise lemoncheesecake would not be able to know the context of the various logging events happening outside/after the test.

I guess that you would have the same behavior with other test frameworks (more "unittest oriented") such as pytest for instance.

**Comment by ndelon** [comment]
Hello @evgeniivas ,

Following my latest answer, I close this ticket.

Best regards
