### ISSUE TITLE
`lcc run` with reporting argument does not run tests

### ISSUE THREAD

**Issue by warangnikhil** [lemoncheesecake/lemoncheesecake#7]
Running `lcc run` with the `--reporting [REPORTING]` argument does not run the test anymore, after v1.0.0

For example, `lcc run --reporting junit` just creates a junit report of the last test run under report directory, as opposed to running a test and saving the html, js, and xml reports under the same, like it did earlier with `--enable-reporting junit`.

Am I missing something?

**Comment by ndelon** [comment]
The 1.0.0 release comes with various backward-incompatible changes among which the CLI is impacted: http://docs.lemoncheesecake.io/en/latest/migrating-to-v1.html#cli

The `--enable-reporting` and `--disable-reporting` arguments have been removed and only the `--reporting` argument has been kept to avoid misunderstandings between those three arguments dealing with the same thing.

The default active reporting backends are :
- `json` (which holds the data for the HTML report),
- `html`
- and `console` (that print messages about what the tests progress).

By using the `--reporting` argument you are replacing this default list by a new one. If you want to __add__ `junit` to the existing ones, then you must do: `lcc run --reporting console json html junit`.
When you only do `lcc run --reporting junit` it means that `junit` will be the only reporting backend in use.

**Comment by warangnikhil** [comment]
Thanks @ndelon. This helps.

**Comment by ndelon** [comment]
Please note that this behavior has been improved in version 1.1.0, now you can do `lcc run --reporting +junit` to add junit to the default reporting backend list (more information here: http://docs.lemoncheesecake.io/en/latest/cli.html#reporting).

**Comment by warangnikhil** [comment]
Thanks for the update @ndelon
