### ISSUE TITLE
Question: How to setup some steps to perform before any of the tests start to run and should be performed only once at the start.

### ISSUE THREAD

**Issue by anarang** [lemoncheesecake/lemoncheesecake#9]
Hi,
I am trying to run the following setup before any of the tests start to run but getting an error:
`
import lemoncheesecake as lcc
import os
from git import Repo

@lcc.fixture(scope="pre_run")
def setup_test_repo():
    repo = Repo()
    repo.clone_from("<repo url>", "test-repo/")
    os.chdir("test-repo/")
    os.system('<perform steps')
`
When trying to run 'lcc run`. I am getting the error:
` File "<path>/fixtures/fixture.py", line 6, in <module>
    @lcc.fixture(scope="pre_run")
TypeError: 'module' object is not callable
`
Can you please help me fix this or guide me how to add a setup step which runs only at the start and only once.

**Comment by ndelon** [comment]
Hello Anisha,

You have done a `import lemoncheesecake as lcc` instead of `import lemoncheesecake.api as lcc`, that's why you get this error.

Regards.

**Comment by anarang** [comment]
Hi @ndelon, thanks a lot for the help, that worked. I have another question here:
So, if I have 10 different files inside suites/ with multiple tests each but I just want the above fixture to run only once as a setup step for all the suites or tests. How can I do that? 
I am calling the fixture as a part of the setup_suite but then that also would run for every suite. How about executing a block of code once for all the tests which also might include opening the browser.
Can you please suggest.
Below is the simplest implementation so far:

`
import lemoncheesecake.api as lcc

class Driver(object):

    def setup_suite(self, setup_test_repo):
        lcc.log_info("Inside setup")
        
    def teardown_suite(self):
        lcc.log_info("inside teardown")
`

**Comment by ndelon** [comment]
If you already use the "pre_run" fixture scope, it already does what you want: the fixture will be evaluated only once, at test startup.

Regards.

**Comment by anarang** [comment]
But I think the pre_run will run for every suite correct, or I should add sequencing and not call this fixture for all tests?
do we have anything similar to post_run, which we can run once after all the suites have finished executing?

**Comment by ndelon** [comment]
No, a fixture with scope "pre_run" will be evaluated only once, no matter it's used in 1 place or 10 places.

About your second question: yes, you can have something like "fixture teardown"; see http://docs.lemoncheesecake.io/en/latest/fixtures.html and look for "fixture teardown".

**Comment by anarang** [comment]
Thanks @ndelon for the quick response, that helped. is it possible to reach out to you on google chat or email for a quicker response?

**Comment by ndelon** [comment]
Well.. due to work and timezone shift, this place remains the most pratical one (at least for me), and everyone could benefit from the questions and answers (as far as they are not too specific).
